[tool.bumpversion]
current_version = "0.2.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "unsupervised/v{new_version}"
tag_message = "unsupervised/v{new_version}"
allow_dirty = false
commit = true
message = "chore: bump version"
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []

[[tool.bumpversion.files]]
filename = "macromol_gym_unsupervised/__init__.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"
